/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author Ralfc
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        pnlFrente = new javax.swing.JPanel();
        lblTitleFrente = new javax.swing.JLabel();
        pnlFrente1 = new javax.swing.JPanel();
        lblPnlTitle1 = new javax.swing.JLabel();
        lblPnlVotos1 = new javax.swing.JLabel();
        lblPnlPorc1 = new javax.swing.JLabel();
        pnlFrente2 = new javax.swing.JPanel();
        lblPnlTitle2 = new javax.swing.JLabel();
        lblPnlVotos2 = new javax.swing.JLabel();
        lblPnlPorc2 = new javax.swing.JLabel();
        pnlFrente3 = new javax.swing.JPanel();
        lblPnlTitle3 = new javax.swing.JLabel();
        lblPnlVotos3 = new javax.swing.JLabel();
        lblPnlPorc3 = new javax.swing.JLabel();
        btnFrentes = new javax.swing.JButton();
        pnlMesas = new javax.swing.JPanel();
        lblTitleMesa = new javax.swing.JLabel();
        lblDescMesa = new javax.swing.JLabel();
        pnlMesa1 = new javax.swing.JPanel();
        lblTitleMesa1 = new javax.swing.JLabel();
        lblJuradoMesa1 = new javax.swing.JLabel();
        lblVotosMesa1 = new javax.swing.JLabel();
        pnlMesa2 = new javax.swing.JPanel();
        lblTitleMesa2 = new javax.swing.JLabel();
        lblJuradoMesa2 = new javax.swing.JLabel();
        lblVotosMesa2 = new javax.swing.JLabel();
        pnlMesa3 = new javax.swing.JPanel();
        lblTitleMesa3 = new javax.swing.JLabel();
        lblJuradoMesa3 = new javax.swing.JLabel();
        lblVotosMesa3 = new javax.swing.JLabel();
        pnlMesa4 = new javax.swing.JPanel();
        lblTitleMesa4 = new javax.swing.JLabel();
        lblJuradoMesa4 = new javax.swing.JLabel();
        lblVotosMesa4 = new javax.swing.JLabel();
        pnlMesa5 = new javax.swing.JPanel();
        lblTitleMesa5 = new javax.swing.JLabel();
        lblJuradoMesa5 = new javax.swing.JLabel();
        lblVotosMesa5 = new javax.swing.JLabel();
        pnlMesa6 = new javax.swing.JPanel();
        lblTitleMesa6 = new javax.swing.JLabel();
        lblJuradoMesa6 = new javax.swing.JLabel();
        lblVotosMesa6 = new javax.swing.JLabel();
        pnlMesa7 = new javax.swing.JPanel();
        lblTitleMesa7 = new javax.swing.JLabel();
        lblJuradoMesa7 = new javax.swing.JLabel();
        lblVotosMesa7 = new javax.swing.JLabel();
        pnlMesa8 = new javax.swing.JPanel();
        lblTitleMesa8 = new javax.swing.JLabel();
        lblJuradoMesa8 = new javax.swing.JLabel();
        lblVotosMesa8 = new javax.swing.JLabel();
        btnMesas = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(824, 728));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 150, 129));
        lblWelcome.setText("Bienvenido (a):");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblSubTitle.setText("Panel Administrativo");
        add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        pnlFrente.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleFrente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleFrente.setForeground(new java.awt.Color(0, 150, 129));
        lblTitleFrente.setText("Frentes destacados");
        pnlFrente.add(lblTitleFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pnlFrente1.setBackground(new java.awt.Color(245, 245, 245));
        pnlFrente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFrente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPnlTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPnlTitle1.setForeground(new java.awt.Color(0, 140, 115));
        lblPnlTitle1.setText("Frente Unidad");
        pnlFrente1.add(lblPnlTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, -1));

        lblPnlVotos1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPnlVotos1.setForeground(new java.awt.Color(0, 150, 129));
        lblPnlVotos1.setText("140 Votos");
        pnlFrente1.add(lblPnlVotos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 51, -1, -1));

        lblPnlPorc1.setForeground(new java.awt.Color(102, 102, 102));
        lblPnlPorc1.setText("50% de los votos");
        pnlFrente1.add(lblPnlPorc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, -1, -1));

        pnlFrente.add(pnlFrente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 214, 130));

        pnlFrente2.setBackground(new java.awt.Color(245, 245, 245));
        pnlFrente2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFrente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPnlTitle2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPnlTitle2.setForeground(new java.awt.Color(0, 140, 115));
        lblPnlTitle2.setText("Frente Unidad");
        pnlFrente2.add(lblPnlTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, -1));

        lblPnlVotos2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPnlVotos2.setForeground(new java.awt.Color(0, 150, 129));
        lblPnlVotos2.setText("140 Votos");
        pnlFrente2.add(lblPnlVotos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 51, -1, -1));

        lblPnlPorc2.setForeground(new java.awt.Color(102, 102, 102));
        lblPnlPorc2.setText("50% de los votos");
        pnlFrente2.add(lblPnlPorc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, -1, -1));

        pnlFrente.add(pnlFrente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 70, 214, 130));

        pnlFrente3.setBackground(new java.awt.Color(245, 245, 245));
        pnlFrente3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFrente3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPnlTitle3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPnlTitle3.setForeground(new java.awt.Color(0, 140, 115));
        lblPnlTitle3.setText("Frente Unidad");
        pnlFrente3.add(lblPnlTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, -1));

        lblPnlVotos3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPnlVotos3.setForeground(new java.awt.Color(0, 150, 129));
        lblPnlVotos3.setText("140 Votos");
        pnlFrente3.add(lblPnlVotos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 51, -1, -1));

        lblPnlPorc3.setForeground(new java.awt.Color(102, 102, 102));
        lblPnlPorc3.setText("50% de los votos");
        pnlFrente3.add(lblPnlPorc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, -1, -1));

        pnlFrente.add(pnlFrente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 70, 214, 130));

        btnFrentes.setBackground(new java.awt.Color(255, 255, 255));
        btnFrentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFrentes.setForeground(new java.awt.Color(0, 150, 129));
        btnFrentes.setText("Ver frentes");
        btnFrentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 150, 129)));
        btnFrentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFrentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFrentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFrentesMouseExited(evt);
            }
        });
        pnlFrente.add(btnFrentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 30));

        add(pnlFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 764, 230));

        pnlMesas.setBackground(new java.awt.Color(255, 255, 255));
        pnlMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleMesa.setForeground(new java.awt.Color(0, 150, 129));
        lblTitleMesa.setText("Votos recolectados");
        pnlMesas.add(lblTitleMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblDescMesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescMesa.setForeground(new java.awt.Color(51, 51, 51));
        lblDescMesa.setText("Votos recogidos por mesas");
        pnlMesas.add(lblDescMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        pnlMesa1.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa1.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa1.setText("Mesa 1");
        pnlMesa1.add(lblTitleMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa1.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa1.setText("Jurado Alejandro M.");
        pnlMesa1.add(lblJuradoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa1.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa1.setText("30 Votos");
        pnlMesa1.add(lblVotosMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 100));

        pnlMesa2.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa2.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa2.setText("Mesa 2");
        pnlMesa2.add(lblTitleMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa2.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa2.setText("Jurado Alejandro M.");
        pnlMesa2.add(lblJuradoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa2.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa2.setText("30 Votos");
        pnlMesa2.add(lblVotosMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, 100));

        pnlMesa3.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa3.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa3.setText("Mesa 3");
        pnlMesa3.add(lblTitleMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa3.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa3.setText("Jurado Alejandro M.");
        pnlMesa3.add(lblJuradoMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa3.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa3.setText("30 Votos");
        pnlMesa3.add(lblVotosMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 170, 100));

        pnlMesa4.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa4.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa4.setText("Mesa 4");
        pnlMesa4.add(lblTitleMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa4.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa4.setText("Jurado Alejandro M.");
        pnlMesa4.add(lblJuradoMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa4.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa4.setText("30 Votos");
        pnlMesa4.add(lblVotosMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, 100));

        pnlMesa5.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa5.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa5.setText("Mesa 5");
        pnlMesa5.add(lblTitleMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa5.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa5.setText("Jurado Alejandro M.");
        pnlMesa5.add(lblJuradoMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa5.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa5.setText("30 Votos");
        pnlMesa5.add(lblVotosMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, 100));

        pnlMesa6.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa6.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa6.setText("Mesa 6");
        pnlMesa6.add(lblTitleMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa6.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa6.setText("Jurado Alejandro M.");
        pnlMesa6.add(lblJuradoMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa6.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa6.setText("30 Votos");
        pnlMesa6.add(lblVotosMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 100));

        pnlMesa7.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa7.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa7.setText("Mesa 7");
        pnlMesa7.add(lblTitleMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa7.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa7.setText("Jurado Alejandro M.");
        pnlMesa7.add(lblJuradoMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa7.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa7.setText("30 Votos");
        pnlMesa7.add(lblVotosMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 170, 100));

        pnlMesa8.setBackground(new java.awt.Color(245, 245, 245));
        pnlMesa8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMesa8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMesa8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleMesa8.setForeground(new java.awt.Color(0, 140, 115));
        lblTitleMesa8.setText("Mesa 8");
        pnlMesa8.add(lblTitleMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        lblJuradoMesa8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuradoMesa8.setForeground(new java.awt.Color(102, 102, 102));
        lblJuradoMesa8.setText("Jurado Alejandro M.");
        pnlMesa8.add(lblJuradoMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        lblVotosMesa8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVotosMesa8.setForeground(new java.awt.Color(0, 150, 129));
        lblVotosMesa8.setText("30 Votos");
        pnlMesa8.add(lblVotosMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        pnlMesas.add(pnlMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 170, 100));

        btnMesas.setBackground(new java.awt.Color(255, 255, 255));
        btnMesas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(0, 150, 129));
        btnMesas.setText("Ver mesas");
        btnMesas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 150, 129)));
        btnMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMesasMouseExited(evt);
            }
        });
        pnlMesas.add(btnMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, 30));

        add(pnlMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 764, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrentesMouseEntered
        btnFrentes.setBackground(new Color(0, 150, 129));
        btnFrentes.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFrentesMouseEntered

    private void btnFrentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrentesMouseExited
        btnFrentes.setBackground(Color.WHITE);
        btnFrentes.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnFrentesMouseExited

    private void btnMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseEntered
        btnMesas.setBackground(new Color(0, 150, 129));
        btnMesas.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMesasMouseEntered

    private void btnMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseExited
        btnMesas.setBackground(Color.WHITE);
        btnMesas.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnMesasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrentes;
    private javax.swing.JButton btnMesas;
    private javax.swing.JLabel lblDescMesa;
    private javax.swing.JLabel lblJuradoMesa1;
    private javax.swing.JLabel lblJuradoMesa2;
    private javax.swing.JLabel lblJuradoMesa3;
    private javax.swing.JLabel lblJuradoMesa4;
    private javax.swing.JLabel lblJuradoMesa5;
    private javax.swing.JLabel lblJuradoMesa6;
    private javax.swing.JLabel lblJuradoMesa7;
    private javax.swing.JLabel lblJuradoMesa8;
    private javax.swing.JLabel lblPnlPorc1;
    private javax.swing.JLabel lblPnlPorc2;
    private javax.swing.JLabel lblPnlPorc3;
    private javax.swing.JLabel lblPnlTitle1;
    private javax.swing.JLabel lblPnlTitle2;
    private javax.swing.JLabel lblPnlTitle3;
    private javax.swing.JLabel lblPnlVotos1;
    private javax.swing.JLabel lblPnlVotos2;
    private javax.swing.JLabel lblPnlVotos3;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitleFrente;
    private javax.swing.JLabel lblTitleMesa;
    private javax.swing.JLabel lblTitleMesa1;
    private javax.swing.JLabel lblTitleMesa2;
    private javax.swing.JLabel lblTitleMesa3;
    private javax.swing.JLabel lblTitleMesa4;
    private javax.swing.JLabel lblTitleMesa5;
    private javax.swing.JLabel lblTitleMesa6;
    private javax.swing.JLabel lblTitleMesa7;
    private javax.swing.JLabel lblTitleMesa8;
    private javax.swing.JLabel lblVotosMesa1;
    private javax.swing.JLabel lblVotosMesa2;
    private javax.swing.JLabel lblVotosMesa3;
    private javax.swing.JLabel lblVotosMesa4;
    private javax.swing.JLabel lblVotosMesa5;
    private javax.swing.JLabel lblVotosMesa6;
    private javax.swing.JLabel lblVotosMesa7;
    private javax.swing.JLabel lblVotosMesa8;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlFrente;
    private javax.swing.JPanel pnlFrente1;
    private javax.swing.JPanel pnlFrente2;
    private javax.swing.JPanel pnlFrente3;
    private javax.swing.JPanel pnlMesa1;
    private javax.swing.JPanel pnlMesa2;
    private javax.swing.JPanel pnlMesa3;
    private javax.swing.JPanel pnlMesa4;
    private javax.swing.JPanel pnlMesa5;
    private javax.swing.JPanel pnlMesa6;
    private javax.swing.JPanel pnlMesa7;
    private javax.swing.JPanel pnlMesa8;
    private javax.swing.JPanel pnlMesas;
    // End of variables declaration//GEN-END:variables
}
