/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logic.FrenteService;
import logic.model.Frente;

/**
 *
 * @author Ralfc
 */
public class FrentesPanel extends javax.swing.JPanel {

    private JTable tabla;
    private DefaultTableModel modeloTable;
    /**
     * Creates new form Frentes
     */
    public FrentesPanel() {
        initComponents();
        
        String[] colums = {"Nombre", "Nro integrantes", "Presidente"};
        modeloTable = new DefaultTableModel(colums, 0);
        tabla = new JTable(modeloTable);
        
        JScrollPane scrollPane = new JScrollPane(tabla);
        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 750, 560));
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 129));
        jLabel1.setText("Frentes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButton1.setText("Agregar Frente");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatos() {
        FrenteService frenteService = new FrenteService();
        ArrayList<Frente> data = frenteService.getFrentes();
        for (Frente f : data) {
            Object[] fila = { f.getNombre(), f.candidatos.size(), f.candidatos.get(0).getNombre() };
            modeloTable.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
